test_runner:
  class: "qiskit_check._test_engine.test_runner.IBMQDeviceRunner"
  args:
    backend_name: "ibmq_armonk"
    provider_hub: "ibm-q"
    provider_group: "open"
    provider_project: "main"
    printer:
      class: "qiskit_check._test_engine.printers.TerminalPrinter"
    tomography:
      class: "qiskit_check._test_engine.state_estimation.tomography.direct_inversion_tomography.DirectInversionTomography"
input_generator_factory:
  class: "qiskit_check._test_engine.generator.HaarInputGeneratorFactory"
