test_runner:
  class: "qiskit_check._test_engine.test_runner.SimulatorTestRunner"
  args:
    simulator_name: "aer_simulator"
    printer:
      class: "qiskit_check._test_engine.printers.TerminalPrinter"
    tomography:
      class: "qiskit_check._test_engine.state_estimation.tomography.direct_inversion_tomography.DirectInversionTomography"
input_generator_factory:
  class: "qiskit_check._test_engine.generator.NaiveDistanceInputGeneratorFactory"
  args:
    single_qubit_generator_factory:
      class: "qiskit_check._test_engine.generator.HaarInputGeneratorFactory"
