test_runner:
  class: "qiskit_check.test_engine.test_runner.SimulatorTestRunner"
  args:
    simulator_name: "aer_simulator"
    printer:
      class: "qiskit_check.test_engine.printers.TerminalPrinter"
input_generator_factory:
  class: "qiskit_check.test_engine.generator.NaiveInputGenerator"
